
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Dec 25 19:54:48 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 36;
  public static final int CONST = 10;
  public static final int CHAR = 6;
  public static final int GE = 19;
  public static final int CASE = 5;
  public static final int REM = 43;
  public static final int SEMI = 45;
  public static final int LPAREN = 26;
  public static final int CONTINUE = 11;
  public static final int MINUS = 28;
  public static final int RPAREN = 47;
  public static final int AND = 2;
  public static final int LT = 27;
  public static final int OR = 34;
  public static final int BOOL = 3;
  public static final int COMMA = 9;
  public static final int CLASS = 7;
  public static final int DIV = 12;
  public static final int PLUS = 35;
  public static final int IF = 22;
  public static final int DOT = 14;
  public static final int LE = 25;
  public static final int EOF = 0;
  public static final int RETURN = 44;
  public static final int MINUSMINUS = 29;
  public static final int LCURVPAREN = 24;
  public static final int EQUAL = 17;
  public static final int NEW = 31;
  public static final int error = 1;
  public static final int MUL = 30;
  public static final int NUMBER = 33;
  public static final int BREAK = 4;
  public static final int IDENT = 21;
  public static final int VOID = 48;
  public static final int SWITCH = 50;
  public static final int NOTSAME = 32;
  public static final int SAME = 51;
  public static final int COLON = 8;
  public static final int LBRACE = 23;
  public static final int ELSE = 15;
  public static final int READ = 42;
  public static final int ENUM = 16;
  public static final int WHILE = 49;
  public static final int RCURVPAREN = 41;
  public static final int RBRACE = 40;
  public static final int PROG = 38;
  public static final int EXTENDS = 18;
  public static final int STRING = 46;
  public static final int QUESTION = 39;
  public static final int GT = 20;
  public static final int PRINT = 37;
  public static final int DO = 13;
}

