
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 27 03:23:03 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 32;
  public static final int CHAR = 51;
  public static final int CONST = 8;
  public static final int GE = 17;
  public static final int CASE = 4;
  public static final int REM = 39;
  public static final int SEMI = 41;
  public static final int LPAREN = 23;
  public static final int CONTINUE = 9;
  public static final int MINUS = 25;
  public static final int RPAREN = 42;
  public static final int AND = 2;
  public static final int LT = 24;
  public static final int OR = 30;
  public static final int BOOL = 49;
  public static final int COMMA = 7;
  public static final int CLASS = 5;
  public static final int DIV = 10;
  public static final int PLUS = 31;
  public static final int IF = 19;
  public static final int DOT = 12;
  public static final int LE = 22;
  public static final int EOF = 0;
  public static final int RETURN = 40;
  public static final int MINUSMINUS = 26;
  public static final int LCURVPAREN = 21;
  public static final int EQUAL = 15;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int MUL = 27;
  public static final int NUMBER = 50;
  public static final int IDENT = 47;
  public static final int BREAK = 3;
  public static final int VOID = 43;
  public static final int SWITCH = 45;
  public static final int NOTSAME = 29;
  public static final int SAME = 46;
  public static final int COLON = 6;
  public static final int LBRACE = 20;
  public static final int ELSE = 13;
  public static final int READ = 38;
  public static final int ENUM = 14;
  public static final int WHILE = 44;
  public static final int RCURVPAREN = 37;
  public static final int RBRACE = 36;
  public static final int EXTENDS = 16;
  public static final int PROG = 34;
  public static final int STRING = 48;
  public static final int QUESTION = 35;
  public static final int GT = 18;
  public static final int PRINT = 33;
  public static final int DO = 11;
}

